Update : JSON response on GetPods + Job Creation
inarix/go-feather-slack-app pull request #6
Opened 2020-12-18 22:18 UTC by saisona

- Now the /pods is responding with all Pods items in an AWS cluster.
 - creation of /migrate that is creating a fake inarix job

 @cesumilo , would you prefer that we say that Inarix will use my private repo as application ? Or do we make this
 repo public and we create a private repo with Inarix that uses my OpenSource go-feather-slack go package ?

 FYI : warning, we still need to add the GoogleAuthentication so we will
 be able to create some pods on both AWS and GCP clusters

Closing #1

2020-12-22 13:27 UTC, saisona commented
> > * Now the /pods is responding with all Pods items in an AWS cluster.
> > * creation of /migrate that is creating a fake inarix job
> > 
> > @cesumilo , would you prefer that we say that Inarix will use my private repo as application ? Or do we make this
> > repo public and we create a private repo with Inarix that uses my OpenSource go-feather-slack go package ?
> > FYI : warning, we still need to add the GoogleAuthentication so we will
> > be able to create some pods on both AWS and GCP clusters
> > Closing #1
> 
> I cannot take this decision alone. If any of the software has been made during office hours, it's owned by Inarix. However, I let you discuss with Artemis about it.

None of all those lines has been made during office hours for that reason :), since then I completely agree with you about the fact that it could be good to ask to Artemis.
However I thought that you could give me a base line that we could follow, so whether I chose to keep thinking about making it open source or I'm starting to build it as it will be used only for Inarix purpose and then I'll have to talk about it with Artemis about what does he wants to do.

2020-12-23 11:31 UTC, cesumilo commented
> > > * Now the /pods is responding with all Pods items in an AWS cluster.
> > > * creation of /migrate that is creating a fake inarix job
> > > 
> > > @cesumilo , would you prefer that we say that Inarix will use my private repo as application ? Or do we make this
> > > repo public and we create a private repo with Inarix that uses my OpenSource go-feather-slack go package ?
> > > FYI : warning, we still need to add the GoogleAuthentication so we will
> > > be able to create some pods on both AWS and GCP clusters
> > > Closing #1
> > 
> > 
> > I cannot take this decision alone. If any of the software has been made during office hours, it's owned by Inarix. However, I let you discuss with Artemis about it.
> 
> None of all those lines has been made during office hours for that reason :), since then I completely agree with you about the fact that it could be good to ask to Artemis.
> However I thought that you could give me a base line that we could follow, so whether I chose to keep thinking about making it open source or I'm starting to build it as it will be used only for Inarix purpose and then I'll have to talk about it with Artemis about what does he wants to do.

Make it open source, it's a good exercice for your futur project. I don't know what will say Inarix, however, I already know some points where you're screw. Let's talk about it in private hehe.

2020-12-23 11:40 UTC, cesumilo requested changes
Some consistency issues and also what would be nice is to extract constant string into constants 👍

2020-12-23 11:40 UTC, cesumilo commented on src/go-feather-slack-app/server/main.go
> +		marchalled_kubernetes_items, err := json.Marshal(pods.Items)
You use snake case here. You're using camel case usually so I guess it's a mistake.

2020-12-24 15:45 UTC, saisona commented on src/go-feather-slack-app/server/main.go
> +		marchalled_kubernetes_items, err := json.Marshal(pods.Items)
nice good idea :)

2020-12-25 21:19 UTC, saisona commented
> Some consistency issues and also what would be nice is to extract constant string into constants 👍

@cesumilo what do you mean by extract constant strings

2021-02-09 20:38 UTC, merged